#!/bin/sh -e

. /usr/share/initramfs-tools/hook-functions

# We use date, hwclock and dumpe2fs
copy_exec /usr/bin/awk /bin
copy_exec /usr/bin/head /bin
copy_exec /usr/bin/bc /bin

copy_exec /usr/bin/strfile /bin
copy_exec /usr/bin/unstr /bin
copy_exec /usr/games/fortune /usr/games/

mkdir -p "$DESTDIR/usr/share/games/fortunes"

cp -p /usr/share/games/fortunes/biglinux-ptbr "$DESTDIR/usr/share/games/fortunes"

cp -p /usr/share/games/fortunes/biglinux-ptbr.dat "$DESTDIR/usr/share/games/fortunes"


cp -p /usr/share/games/fortunes/fortunes "$DESTDIR/usr/share/games/fortunes"

cp -p /usr/share/games/fortunes/fortunes.dat "$DESTDIR/usr/share/games/fortunes"
