#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}




# ANSI COLORS
CRE="
[K"
NORMAL="[0;39m"
# RED: Failure or error message
RED="[1;1m"
# GREEN: Success message
GREEN="[1;32m"
# YELLOW: Descriptions
YELLOW="[1;33m"
# BLUE: System messages
BLUE="[1;34m"
# MAGENTA: Found devices or drivers
MAGENTA="[1;56m"
# CYAN: Questions
CYAN="[1;36m"
# BOLD WHITE: Hint
WHITE="[1;37m"

corPadrao="[0m"
preto="[0;30m"
vermelho="[0;31m"
verde="[0;32m"
marrom="[0;33m"
azul="[0;34m"
purple="[0;35m"
cyan="[0;36m"
cinzaClaro="[0;37m"
pretoCinza="[1;30m"
vermelhoClaro="[1;31m"
verdeClaro="[1;32m"
amarelo="[1;33m"
azulClaro="[1;34m"
purpleClaro="[1;35m"
cyanClaro="[1;36m"
branco="[1;37m"


if [ "$(grep " init=/usr/bin/isocheck.sh " /proc/cmdline)" = "" ]; then

    if [ "$(grep "init *=" /proc/cmdline)" != "" ]; then
        /usr/bin/reboot
    fi

    if [ "$(grep "init=" /proc/cmdline)" != "" ]; then
        /usr/bin/reboot
    fi 
fi

echo -n "
${vermelho} ██████  ██  ██████  ██      ██ ███    ██ ██    ██ ██   ██ 
${verde} ██   ██ ██ ██       ██      ██ ████   ██ ██    ██  ██ ██  
${azulClaro} ██████  ██ ██   ███ ██      ██ ██ ██  ██ ██    ██   ███   
${cinzaClaro} ██   ██ ██ ██    ██ ██      ██ ██  ██ ██ ██    ██  ██ ██  
${pretoCinza} ██████  ██  ██████  ███████ ██ ██   ████  ██████  ██   ██ 
"

KERNEL="$(uname -r)"
#echo "
#     ${YELLOW}BBB  I  GGG  ${GREEN}  L    I NN    N U   U X   X
#     ${YELLOW}B  B I G     ${GREEN}  L    I N N   N U   U  X X 
#     ${YELLOW}BBB  I G GGG ${GREEN}  L    I N  N  N U   U   X  
#     ${YELLOW}B  B I G   G ${GREEN}  L    I N   N N U   U  X X 
#     ${YELLOW}BBB  I  GGG  ${GREEN}  LLLL I N    NN  UUU  X   X
echo "
${WHITE}                  www.biglinux.com.br





"

if [ "$(grep "locale=pt" /proc/cmdline)" != "" ]
then
    /usr/games/fortune biglinux-ptbr
else
    /usr/games/fortune
fi



echo -n "${NORMAL}

"




