#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

if [ "$(grep " init=/usr/bin/isocheck.sh " /proc/cmdline)" = "" ]; then

    if [ "$(grep "init *=" /proc/cmdline)" != "" ]; then
        /usr/bin/reboot
    fi

    if [ "$(grep "init=" /proc/cmdline)" != "" ]; then
        /usr/bin/reboot
    fi 
fi


if [ "$(grep "locale=pt" /proc/cmdline)" != "" ]
then
    #/usr/games/fortune biglinux-ptbr
    
echo "Aguarde um momento..."
else
    #/usr/games/fortune
echo "Please wait..."
fi


